<#
.SYNOPSIS
  Evaluates a future external shadow-candidate request without dispatching it.
#>
param([Parameter(Mandatory=$true)][string]$RequestPath,[string]$RegistryPath='',[switch]$PassThru)
$ErrorActionPreference='Stop';$root=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;if([string]::IsNullOrWhiteSpace($RegistryPath)){$RegistryPath=Join-Path $root '.qianlima\shadow-candidate-provider-registry.json'};$request=Get-Content -LiteralPath $RequestPath -Raw -Encoding UTF8|ConvertFrom-Json;$registry=Get-Content -LiteralPath $RegistryPath -Raw -Encoding UTF8|ConvertFrom-Json;$issues=[System.Collections.Generic.List[string]]::new();$provider=@($registry.providers|?{$_.provider_id-eq$request.provider_id})|Select-Object -First 1
if($null-eq$provider){[void]$issues.Add('unknown_provider')}else{if(-not$provider.enabled){[void]$issues.Add('provider_disabled')};if([string]::IsNullOrWhiteSpace([string]$request.model_version)-or[string]$request.model_version-match'must_be_pinned'){[void]$issues.Add('version_not_pinned')};if(@($provider.allowed_data)-notcontains$request.data_classification){[void]$issues.Add('data_classification_denied')};if([int]$request.max_calls-gt[int]$provider.max_calls-or[double]$request.max_cost_usd-gt[double]$provider.max_cost_usd-or[int]$request.max_latency_ms-gt[int]$provider.max_latency_ms){[void]$issues.Add('budget_exceeded')};if(@($provider.tools).Count-or$provider.mcp-or$provider.file_export-or$provider.business_write){[void]$issues.Add('provider_scope_not_readonly')}}
if(-not$registry.network_dispatch_enabled){[void]$issues.Add('network_dispatch_disabled')};if([string]$request.risk_level-ne'L3'){[void]$issues.Add('shadow_candidate_requires_L3')};if([string]::IsNullOrWhiteSpace([string]$request.task_approval_ref)){[void]$issues.Add('task_approval_required')};foreach($f in @('fusion_plan_ref','collaboration_contract_ref','employee_id','agent_id','claim_pack_output_ref')){if([string]::IsNullOrWhiteSpace([string]$request.$f)){[void]$issues.Add($f+'_required')}}
$result=[ordered]@{status=if($issues.Count){'denied'}else{'eligible_for_dispatch'};provider_id=$request.provider_id;task_id=$request.task_id;issues=@($issues);credential_ref=if($null-ne$provider){$provider.credential_ref}else{$null};external_call_made=$false;credential_value_read=$false;permissions_granted=$false;primary_result_affected=$false;dispatch_authority='none'};if($PassThru){$result|ConvertTo-Json -Depth 8}else{[PSCustomObject]$result|Format-List};if($issues.Count){exit 1}
