<#
.SYNOPSIS
  Enforces evaluation-card transitions without applying a production change.
#>
param([Parameter(Mandatory=$true)][string]$EvaluationCardPath,[Parameter(Mandatory=$true)][string]$CandidateValidationPath,[ValidateSet('Evaluate','AuthorizeCanary','ConvergeCanary')][string]$Phase='Evaluate',[string]$HumanApprovalRef='',[switch]$PassThru)
$ErrorActionPreference='Stop';$root=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;$schema=Get-Content -LiteralPath (Join-Path $root '.qianlima\improvement-evaluation-card-schema.json') -Raw -Encoding UTF8|ConvertFrom-Json;$card=Get-Content -LiteralPath $EvaluationCardPath -Raw -Encoding UTF8|ConvertFrom-Json;$validation=Get-Content -LiteralPath $CandidateValidationPath -Raw -Encoding UTF8|ConvertFrom-Json;$issues=[System.Collections.Generic.List[string]]::new()
foreach($f in @($schema.required_fields)){if($null-eq$card.$f-or[string]::IsNullOrWhiteSpace([string]$card.$f)){[void]$issues.Add("${f}_required")}};if($validation.status-ne'passed'-or$validation.candidate_id-ne$card.candidate_id-or$validation.candidate_content_sha256-ne$card.candidate_content_sha256){[void]$issues.Add('candidate_validation_lineage_mismatch')};$policy=$schema.object_policy.([string]$card.object_type);if($null-eq$policy){[void]$issues.Add('object_type_denied')};if(@($card.immutable_boundaries)-notcontains'no_permission_expansion'-or@($card.immutable_boundaries)-notcontains'no_data_scope_expansion'-or@($card.immutable_boundaries)-notcontains'no_automatic_production_change'){[void]$issues.Add('immutable_boundaries_incomplete')};if($card.replay_result.status-ne'passed'){[void]$issues.Add('frozen_replay_not_passed')};if($card.simulation_result.status-ne'passed'){[void]$issues.Add('simulation_not_passed')};if($card.independent_verification.status-ne'passed'-or$card.independent_verification.verifier_id-eq$card.independent_verification.proposer_id){[void]$issues.Add('independent_verification_not_passed')};if(@($card.rollback_conditions).Count-lt1){[void]$issues.Add('rollback_conditions_required')}
$recommendationOnly=@('permission','data_scope','budget','external_call','risk_rule','audit_rule','deletion_policy') -contains [string]$card.object_type;$next='frozen';if(-not$issues.Count){switch($Phase){'Evaluate'{$next=if($recommendationOnly){'recommendation_only'}else{'awaiting_human'}}'AuthorizeCanary'{if($recommendationOnly){[void]$issues.Add('protected_object_cannot_enter_canary')}elseif([string]::IsNullOrWhiteSpace($HumanApprovalRef)-or$card.approval.status-ne'approved'-or$card.approval.approval_ref-ne$HumanApprovalRef){[void]$issues.Add('named_human_approval_required')}else{$next='canary_authorized'}}'ConvergeCanary'{if($recommendationOnly){[void]$issues.Add('protected_object_cannot_release')}elseif($card.approval.status-ne'approved'){[void]$issues.Add('human_approval_required')}elseif($card.canary_result.status-ne'passed'-or[bool]$card.canary_result.rollback_triggered){$next='rollback_required'}elseif(-not[bool]$card.canary_result.quality_guard_passed-or-not[bool]$card.canary_result.latency_guard_passed-or-not[bool]$card.canary_result.safety_guard_passed){$next='rollback_required'}else{$next='release_candidate'}}}}
if($issues.Count){$next='frozen'};$result=[ordered]@{status=if($issues.Count){'blocked'}else{'allowed'};phase=$Phase;candidate_id=$card.candidate_id;object_type=$card.object_type;next_state=$next;issues=@($issues);human_approval_required=$true;automatic_release=$false;production_change=$false;permission_change='none';data_scope_change='none';budget_change='none';external_call_change='none';rollback_evidence_preserved=($next-eq'rollback_required');external_calls=$false};if($PassThru){$result|ConvertTo-Json -Depth 10}else{[pscustomobject]$result|Format-List};if($issues.Count){exit 1}
