<#
.SYNOPSIS
  Converts an offline Skill/MCP scan report into governed admission evidence.
#>
param([Parameter(Mandatory=$true)][string]$IntakePath,[Parameter(Mandatory=$true)][string]$ScanReportPath,[switch]$PassThru)
$ErrorActionPreference='Stop';$intake=Get-Content -LiteralPath $IntakePath -Raw -Encoding UTF8|ConvertFrom-Json;$scan=Get-Content -LiteralPath $ScanReportPath -Raw -Encoding UTF8|ConvertFrom-Json;$issues=[System.Collections.Generic.List[string]]::new();$conditions=[System.Collections.Generic.List[string]]::new()
foreach($f in @('artifact_id','artifact_type','source_type','source_ref','version','content_sha256','commit_sha','author_ref','dependency_manifest_hash','data_classification','declared_capabilities','requested_permissions')){if($null-eq$intake.$f-or[string]::IsNullOrWhiteSpace([string]$intake.$f)){[void]$issues.Add("intake_${f}_required")}};foreach($f in @('scanner_id','scanner_version','scanned_at','artifact_content_sha256','dependency_manifest_hash','offline_static_completed','network_used','llm_mode','observed_capabilities','findings','rescan_reasons')){if($null-eq$scan.$f){[void]$issues.Add("scan_${f}_required")}}
if($intake.artifact_type-notin@('skill','mcp_connector')){[void]$issues.Add('artifact_type_denied')};if($intake.source_type-notin@('git_url','archive','internal_artifact')){[void]$issues.Add('source_type_denied')};if([string]$intake.content_sha256-notmatch'^[a-fA-F0-9]{64}$'-or$scan.artifact_content_sha256-ne$intake.content_sha256){[void]$issues.Add('artifact_hash_mismatch')};if($scan.dependency_manifest_hash-ne$intake.dependency_manifest_hash){[void]$issues.Add('dependency_manifest_mismatch')};if(-not[bool]$scan.offline_static_completed){[void]$issues.Add('offline_static_scan_required')};if([bool]$scan.network_used-and-not[bool]$intake.dependency_network_approved){[void]$issues.Add('unapproved_dependency_network_use')}
if($scan.llm_mode-in@('external_llm','approved_external_llm')-and$intake.data_classification-in@('confidential_reference_only','restricted_secret')){[void]$issues.Add('external_llm_source_disclosure_denied')};if($scan.llm_mode-notin@('none','approved_internal_llm','approved_external_llm')){[void]$issues.Add('invalid_llm_mode')}
$declared=@($intake.declared_capabilities);$observed=@($scan.observed_capabilities);$undeclared=@($observed|Where-Object{$declared-notcontains$_});$dangerous=@('enumerate_user_home','read_environment_variables','read_credentials','network_access','filesystem_write','execute_shell','install_plugin','spawn_process','arbitrary_mcp','external_send');$dangerousMismatch=@($undeclared|Where-Object{$_-in$dangerous});if($dangerousMismatch.Count){[void]$issues.Add('dangerous_undeclared_capability')};if($undeclared.Count-and-not$dangerousMismatch.Count){[void]$conditions.Add('non_dangerous_capability_mismatch_review')}
$severities=@($scan.findings|ForEach-Object{[string]$_.severity});if(@($severities|Where-Object{$_-in@('critical','high')}).Count){[void]$issues.Add('high_severity_static_finding')};if(@($severities|Where-Object{$_-eq'medium'}).Count){[void]$conditions.Add('medium_findings_require_review')}
if($intake.artifact_type-eq'mcp_connector'){if($scan.transport-eq'http'-and-not[bool]$scan.authentication_present){[void]$issues.Add('unauthenticated_http_mcp_denied')};if($scan.transport-eq'http'-and$scan.bind_address-notin@('127.0.0.1','::1')){[void]$issues.Add('non_loopback_mcp_bind_denied')};if([bool]$scan.required_on_conversation_start){[void]$issues.Add('conversation_start_dependency_denied')}}
foreach($trigger in @($intake.change_flags)){if(@($scan.rescan_reasons)-notcontains$trigger){[void]$issues.Add("required_rescan_evidence_missing:$trigger")}};$decision=if($issues.Count){'denied'}elseif($conditions.Count){'conditional'}else{'approved'};$safeCapabilities=@($declared|Where-Object{$_-notin$dangerous});$evidenceId="skill-intake-$($intake.artifact_id)-$([Guid]::NewGuid().ToString('n'))"
$result=[ordered]@{status=$decision;admission_evidence=[ordered]@{evidence_id=$evidenceId;artifact_id=$intake.artifact_id;artifact_type=$intake.artifact_type;source_type=$intake.source_type;source_ref=$intake.source_ref;version=$intake.version;commit_sha=$intake.commit_sha;content_sha256=([string]$intake.content_sha256).ToLowerInvariant();dependency_manifest_hash=$intake.dependency_manifest_hash;author_ref=$intake.author_ref;scanner_id=$scan.scanner_id;scanner_version=$scan.scanner_version;scanned_at=$scan.scanned_at;static_findings=@($scan.findings);declared_capabilities=$declared;observed_capabilities=$observed;undeclared_capabilities=$undeclared;issues=@($issues);conditions=@($conditions)};minimum_capability_contract=[ordered]@{capabilities=$safeCapabilities;global_permissions=@();network_access='none';write_access='none';credential_access='none';task_grant_required=$true;revocable=$true};human_confirmation_required=$true;security_review_required=($decision-ne'approved');isolated_trial_required=($decision-ne'denied');install_authorized=$false;global_enable_authorized=$false;scan_is_sandbox=$false;external_calls=$false;permissions_granted=$false};if($PassThru){$result|ConvertTo-Json -Depth 12}else{[pscustomobject]$result|Format-List};if($decision-eq'denied'){exit 1}
