param(
  [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
  [string]$RunId = "$(Get-Date -Format 'yyyy-MM-dd')_manual_001",
  [string]$TaskName = 'replace_me',
  [string]$WorkflowId = 'replace_me',
  [string]$ModelProvider = 'unknown',
  [string]$ModelName = 'unknown',
  [string]$OutputFile = 'replace_me',
  [int]$InputTokens = 0,
  [int]$OutputTokens = 0,
  [int]$CachedInputTokens = 0,
  [int]$ReasoningTokens = 0,
  [decimal]$EstimatedCost = 0,
  [decimal]$BaselineCost = 0,
  [decimal]$EstimatedSavings = 0,
  [decimal]$SavingsRatePct = 0,
  [decimal]$CostLimit = 0,
  [string]$CostStatus = 'estimate',
  [string]$SavingsSource = 'unknown',
  [string]$ContinueOrStop = 'continue',
  [switch]$TaskSuccess,
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

$ledgerDir = Join-Path $Root 'usage-ledger'
if (-not (Test-Path -LiteralPath $ledgerDir -PathType Container)) {
  New-Item -ItemType Directory -Path $ledgerDir | Out-Null
}

$safeRunId = $RunId -replace '[^A-Za-z0-9_.-]', '-'
$path = Join-Path $ledgerDir "$safeRunId.yaml"
if ((Test-Path -LiteralPath $path -PathType Leaf) -and (-not $Force)) {
  throw "Usage ledger already exists: $path. Re-run with -Force to overwrite."
}

$totalTokens = $InputTokens + $OutputTokens + $CachedInputTokens + $ReasoningTokens
$computedSavings = $EstimatedSavings
if (($computedSavings -eq 0) -and ($BaselineCost -gt 0)) {
  $computedSavings = $BaselineCost - $EstimatedCost
}

$computedSavingsRate = $SavingsRatePct
if (($computedSavingsRate -eq 0) -and ($BaselineCost -gt 0)) {
  $computedSavingsRate = [decimal]::Round(($computedSavings / $BaselineCost) * 100, 2)
}

$computedCostStatus = $CostStatus
if (($CostLimit -gt 0) -and ($EstimatedCost -gt $CostLimit)) {
  $computedCostStatus = 'over_limit'
  if ($ContinueOrStop -eq 'continue') {
    $ContinueOrStop = 'needs_confirmation'
  }
}

$date = (Get-Date).ToString('yyyy-MM-dd')
$successValue = if ($TaskSuccess) { 'true' } else { 'false' }

$content = @"
run:
  run_id: $safeRunId
  date: $date
  task_name: $TaskName
  workflow_id: $WorkflowId
  model_provider: $ModelProvider
  model_name: $ModelName

token_usage:
  actual:
    input_tokens: $InputTokens
    output_tokens: $OutputTokens
    cached_input_tokens: $CachedInputTokens
    reasoning_tokens: $ReasoningTokens
    total_tokens: $totalTokens

cost:
  currency: USD
  estimated_cost: $EstimatedCost
  baseline_cost: $BaselineCost
  estimated_savings: $computedSavings
  estimated_savings_rate_pct: $computedSavingsRate
  cost_limit: $CostLimit
  cost_status: $computedCostStatus
  savings_source: $SavingsSource
  continue_or_stop: $ContinueOrStop
  note: Replace placeholder values when exact model metering is available.

realtime_cost_card:
  visible_to_user: true
  current_estimated_cost_usd: $EstimatedCost
  cost_limit_usd: $CostLimit
  baseline_cost_usd: $BaselineCost
  estimated_savings_usd: $computedSavings
  estimated_savings_rate_pct: $computedSavingsRate
  primary_savings_source: $SavingsSource
  continue_or_stop: $ContinueOrStop

context:
  startup_profile: unknown
  files_loaded: []
  compression_used: unknown
  context_policy: .qianlima/context-policy.yaml
  loaded_file_count: 0

result:
  output_file: $OutputFile
  data_sources_used: []
  user_visible_cost_summary: true
  savings_summary_present: true
  task_success: $successValue
  user_edit_required: unknown
  source_citation_present: unknown
  elapsed_seconds: 0
  performance_notes: replace_me
  notes: Generated by new-usage-record.ps1.
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
Write-Host "Usage ledger created: $path"
