<##
.SYNOPSIS
  Regression tests for task-scoped memory reads.
  Uses synthetic memory and grants only; no memory contents are returned.
##>
param([switch]$PassThru)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$validator = Join-Path $PSScriptRoot 'validate-memory-read.ps1'
$memoryRoot = Join-Path $projectRoot 'memory\cards\asin'
$grantRoot = Join-Path $projectRoot '.qianlima\run-traces\delegation-grants'
$requestRoot = Join-Path $projectRoot '.qianlima\run-traces\memory-read-tests'
$stamp = (Get-Date).ToString('yyyyMMddHHmmssfff')
New-Item -ItemType Directory -Path $memoryRoot,$grantRoot,$requestRoot -Force | Out-Null
function Write-Json($Value, [string]$Path) { [IO.File]::WriteAllText($Path, ($Value | ConvertTo-Json -Depth 15), [Text.UTF8Encoding]::new($false)); return $Path }
function New-Memory([string]$State = 'current') { return [ordered]@{ memory_id = "memory-read-$stamp"; kind = 'fact'; state = $State; fact = 'Synthetic sanitized memory fact.'; source_refs = @('synthetic-source'); observed_at = (Get-Date).ToUniversalTime().ToString('o'); valid_from = (Get-Date).ToUniversalTime().AddHours(-1).ToString('o'); valid_to = (Get-Date).ToUniversalTime().AddHours(1).ToString('o'); scope = 'task_selected_sources_only'; confidence = 'high'; classification = 'internal_sanitized'; created_by = 'synthetic-test'; version = 1 } }
function New-Grant([string]$Name = 'valid', [datetime]$Expires = (Get-Date).ToUniversalTime().AddMinutes(10)) { return [ordered]@{ schema_version = 1; contract_type = 'qianlima_delegation_grant'; grant_id = "memory-read-grant-$Name-$stamp"; agent_id = 'evidence_checker'; task_id = "memory-read-task-$stamp"; work_order_id = "memory-read-order-$stamp"; data_refs = @('memory://asin/synthetic'); allowed_tools = @('read_memory'); budget = [ordered]@{ max_steps = 2; max_tool_calls = 1 }; risk_ceiling = 'L2'; expires_at = $Expires.ToString('o'); verifier_agent_id = 'independent-evaluator'; can_delegate = $false; network_access = 'none'; write_access = 'none'; status = 'issued' } }
function New-Request($Grant, [string]$View = 'current') { return [ordered]@{ request_id = "memory-read-request-$View-$stamp"; task_id = $Grant.task_id; grant_id = $Grant.grant_id; agent_id = $Grant.agent_id; memory_refs = @('memory://asin/synthetic'); requested_state_view = $View; requested_scope = 'task_selected_sources_only'; risk_level = 'L2'; max_items = 1; purpose = 'Synthetic state-aware evidence lookup.' } }
function Invoke-ExpectedFailure([string]$RequestPath, [string]$GrantPath, [string]$MemoryPath, [string]$Expected) { $old = $ErrorActionPreference; $ErrorActionPreference = 'Continue'; $out = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $validator -RequestPath $RequestPath -GrantPath $GrantPath -MemoryPath $MemoryPath -PassThru 2>&1); $code = $LASTEXITCODE; $ErrorActionPreference = $old; return ($code -ne 0 -and ($out -join "`n") -match $Expected) }
function Add-Case([System.Collections.Generic.List[object]]$Cases, [string]$Name, [bool]$Passed) { $Cases.Add([PSCustomObject]@{ name = $Name; passed = $Passed }) }
$cases = [System.Collections.Generic.List[object]]::new()
$memoryPath = Write-Json (New-Memory) (Join-Path $memoryRoot "memory-read-$stamp.json")
$grant = New-Grant; $grantPath = Write-Json $grant (Join-Path $grantRoot "$($grant.grant_id).json"); $requestPath = Write-Json (New-Request $grant) (Join-Path $requestRoot "valid-$stamp.json")
$valid = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $validator -RequestPath $requestPath -GrantPath $grantPath -MemoryPath $memoryPath -PassThru | ConvertFrom-Json); Add-Case $cases 'valid_task_scoped_read' ($valid.status -eq 'allowed' -and $valid.contents_returned -eq $false)
$broker = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'invoke-memory-broker.ps1') -RequestPath $requestPath -GrantPath $grantPath -MemoryPath $memoryPath -PassThru | ConvertFrom-Json); Add-Case $cases 'broker_returns_minimum_pack_only' ($broker.status -eq 'allowed' -and $broker.memory_pack.memory_id -eq 'memory-read-' + $stamp -and $broker.full_memory_returned -eq $false -and $broker.raw_memory_recorded -eq $false)
$compat = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'get-qianlima-memory-card.ps1') -EntityType asin -EntityId "memory-read-$stamp" -RequestPath $requestPath -GrantPath $grantPath -AsJson | ConvertFrom-Json); Add-Case $cases 'legacy_memory_entrypoint_is_brokered' ($compat.status -eq 'allowed' -and $compat.full_memory_returned -eq $false)
$brokeredContext = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'invoke-brokered-context.ps1') -TaskText 'Synthetic context with governed memory.' -ContextLevel L1 -AutoStart -MemoryRequestPath $requestPath -MemoryGrantPath $grantPath -MemoryPath $memoryPath -PassThru | ConvertFrom-Json); Add-Case $cases 'context_loader_uses_memory_broker' ($brokeredContext.status -eq 'ready' -and $brokeredContext.memory_gate_used -eq $true -and $brokeredContext.memory.status -eq 'allowed')
$badTask = New-Request $grant; $badTask.task_id = 'other-task'; Add-Case $cases 'task_mismatch_denied' (Invoke-ExpectedFailure (Write-Json $badTask (Join-Path $requestRoot "bad-task-$stamp.json")) $grantPath $memoryPath 'task_grant_mismatch')
$badRef = New-Request $grant; $badRef.memory_refs = @('memory://asin/other'); Add-Case $cases 'memory_ref_outside_grant_denied' (Invoke-ExpectedFailure (Write-Json $badRef (Join-Path $requestRoot "bad-ref-$stamp.json")) $grantPath $memoryPath 'memory_ref_outside_grant')
$expired = New-Grant 'expired' (Get-Date).ToUniversalTime().AddMinutes(-1); $expiredPath = Write-Json $expired (Join-Path $grantRoot "$($expired.grant_id).json"); Add-Case $cases 'expired_grant_denied' (Invoke-ExpectedFailure (Write-Json (New-Request $expired) (Join-Path $requestRoot "expired-$stamp.json")) $expiredPath $memoryPath 'grant_expired')
$revoked = New-Grant 'revoked'; $revokedPath = Write-Json $revoked (Join-Path $grantRoot "$($revoked.grant_id).json"); $revocationPath = Join-Path $projectRoot '.qianlima\run-traces\grant-revocations.jsonl'; [IO.File]::AppendAllText($revocationPath, (([ordered]@{ grant_id = $revoked.grant_id; task_id = $revoked.task_id; agent_id = $revoked.agent_id } | ConvertTo-Json -Compress) + [Environment]::NewLine), [Text.UTF8Encoding]::new($false)); Add-Case $cases 'revoked_grant_denied' (Invoke-ExpectedFailure (Write-Json (New-Request $revoked) (Join-Path $requestRoot "revoked-$stamp.json")) $revokedPath $memoryPath 'grant_revoked')
$historicalMemoryPath = Write-Json (New-Memory 'historical') (Join-Path $memoryRoot "memory-read-historical-$stamp.json"); Add-Case $cases 'historical_memory_denied_in_current_view' (Invoke-ExpectedFailure $requestPath $grantPath $historicalMemoryPath 'non_current_memory_in_current_view')
$l4 = New-Request $grant; $l4.risk_level = 'L4'; Add-Case $cases 'l4_requires_original_source_reload' (Invoke-ExpectedFailure (Write-Json $l4 (Join-Path $requestRoot "l4-$stamp.json")) $grantPath $memoryPath 'L4_requires_original_source_reload')
$badAgent = New-Request $grant; $badAgent.agent_id = 'other-agent'; Add-Case $cases 'agent_mismatch_denied' (Invoke-ExpectedFailure (Write-Json $badAgent (Join-Path $requestRoot "bad-agent-$stamp.json")) $grantPath $memoryPath 'agent_grant_mismatch')
$failed = @($cases | Where-Object { -not $_.passed }); $result = [PSCustomObject]@{ passed = ($failed.Count -eq 0); cases = @($cases); contents_returned = $false; external_calls = $false; raw_memory_recorded = $false }; if ($PassThru) { $result | ConvertTo-Json -Depth 12 } else { $cases | Format-Table -AutoSize }; if ($failed.Count -gt 0) { throw "Memory read regression failed: $($failed.name -join ', ')" }
