<##
.SYNOPSIS
  Regression tests for Constitution -> Specify -> Analyze -> Converge.
##>
param([switch]$PassThru)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$newSpec = Join-Path $PSScriptRoot 'new-agent-admission-spec.ps1'; $analyze = Join-Path $PSScriptRoot 'analyze-agent-admission-spec.ps1'; $converge = Join-Path $PSScriptRoot 'converge-agent-admission-spec.ps1'
$draftRoot = Join-Path $projectRoot '.qianlima\specifications\drafts'; $stamp=(Get-Date).ToString('yyyyMMddHHmmssfff')
$specId="spec-test-$stamp"; $specPath=Join-Path $draftRoot "$specId.json"
$complexityPath=Join-Path $projectRoot ".qianlima\evolution\candidates\spec-complexity-$stamp.json"
$complexity=[ordered]@{proposal_id="spec-complexity-$stamp";proposal_version='1.0.0';lifecycle_state='shadow_converged';target_layer='specification';change_type='new_verifier';goal='Synthetic independent verification gate.';single_agent_sufficient=$false;independent_benefit=[ordered]@{measured_metric='evidence_gap_rate';baseline_value=0.5;candidate_value=0.8;proven=$true};input_contract=[ordered]@{schema_ref='.qianlima/specifications/trace-contract.json';accepted_inputs=@('sanitized_trace_metadata');rejected_inputs=@('raw_prompt')};output_contract=[ordered]@{schema_ref='.qianlima/specifications/trace-contract.json';produced_artifacts=@('verification_report');verification_status='passed'};failure_terminals=@([ordered]@{condition='conflict';terminal_state='needs_human';authority_action='freeze_and_revoke'});permission_impact=[ordered]@{expands_permissions=$false;attack_surface_change='none'};simulation_evidence=[ordered]@{status='passed';report_ref='.qianlima/evolution/eval-cases/spec-synthetic.json';case_count=2;failure_injection_cases=@('conflict','expiry');terminal_state_checked=$true;source_classification='internal_sanitized'};independent_verifier=[ordered]@{verifier_id='spec-independent-evaluator';independence_basis='Separate synthetic rule checker.'};proposed_by_agent_id='spec-proposer';rollback_plan=[ordered]@{rollback_ref='.qianlima/snapshots/spec-baseline';trigger='Any regression'};human_approval=[ordered]@{status='pending';approval_ref=$null};proposed_change=[ordered]@{auto_apply=$false;production_change=$false};privacy=[ordered]@{sanitized=$true;raw_data_included=$false;secrets_included=$false}}
[IO.File]::WriteAllText($complexityPath,($complexity|ConvertTo-Json -Depth 15),[Text.UTF8Encoding]::new($false))
& $newSpec -SpecId $specId -AgentId codewhale_worker -Goal 'Verify one sanitized evidence reference.' -RiskLevel L2 -DataScope internal_sanitized -RunnerId docker_local_mock -OutputPath $specPath | Out-Null
$analysis = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $analyze -SpecPath $specPath -ComplexityProposalPath $complexityPath -PassThru | ConvertFrom-Json
$converged = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $converge -SpecPath $specPath -AnalysisPath $analysis.analysis_path -Mode Shadow -EvidenceStatus passed -RunnerStatus validated_dry_run -PassThru | ConvertFrom-Json
function Test-MissingComplexityGate([string]$Analyzer, [string]$Spec) {
  $old = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  try { $output = @(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Analyzer -SpecPath $Spec -PassThru 2>&1); return (($output -join "`n") -match 'ComplexityProposalPath') }
  finally { $ErrorActionPreference = $old }
}
$cases=[System.Collections.Generic.List[object]]::new();$cases.Add([PSCustomObject]@{name='specify_creates_contract';passed=((Get-Content $specPath -Raw|ConvertFrom-Json).lifecycle_state -eq 'specified')});$cases.Add([PSCustomObject]@{name='analyze_passes_valid_spec';passed=($analysis.status -eq 'passed' -and $analysis.complexity_admission.status -eq 'passed')});$cases.Add([PSCustomObject]@{name='shadow_converges_without_production_change';passed=($converged.status -eq 'shadow_converged' -and $converged.production_change -eq $false)});
$invalidPath=Join-Path $draftRoot "invalid-$stamp.json";$invalid=Get-Content $specPath -Raw|ConvertFrom-Json;$invalid.risk_level='L4';$invalid.rollback_plan.required=$false;$invalid.approval_state.human_confirmation_required=$false;[IO.File]::WriteAllText($invalidPath,($invalid|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false));$cases.Add([PSCustomObject]@{name='analyze_blocks_invalid_L4';passed=((& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $analyze -SpecPath $invalidPath -ComplexityProposalPath $complexityPath -PassThru 2>&1|Out-String) -match 'L4_rollback_or_snapshot_missing')});$cases.Add([PSCustomObject]@{name='analyze_requires_complexity_gate';passed=(Test-MissingComplexityGate $analyze $specPath)});$cases.Add([PSCustomObject]@{name='promote_requires_human_ref';passed=((& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $converge -SpecPath $specPath -AnalysisPath $analysis.analysis_path -Mode Promote -EvidenceStatus passed -RunnerStatus validated_dry_run 2>&1|Out-String) -match 'human_approval_ref_required')});
$boundary=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'check-harness-boundary.ps1') -PassThru|ConvertFrom-Json;$cases.Add([PSCustomObject]@{name='core_harness_unchanged';passed=($boundary.status -eq 'pass')});$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count -eq 0);cases=@($cases);core_files_changed_by_test=$false;production_change=$false};if($PassThru){$result|ConvertTo-Json -Depth 10}else{$cases|Format-Table -AutoSize};if($failed.Count -gt 0){throw "Spec-driven governance regression failed: $($failed.name -join ', ')"}
