<# .SYNOPSIS Offline regression for policy-first enterprise evidence admission. #>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$root=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;$tmp=Join-Path $root '.qianlima\tmp\enterprise-data-admission';New-Item -ItemType Directory -Path $tmp -Force|Out-Null;$runner=Join-Path $PSScriptRoot 'invoke-enterprise-data-admission.ps1';$now=(Get-Date).ToUniversalTime();$hash='a'*64
function W($n,$v){$p=Join-Path $tmp $n;[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false));$p}
$grant=[ordered]@{grant_id='g1';task_id='t1';agent_id='external-research';organization_id='org1';department_id='dept1';project_id='project1';device_id='device1';data_refs=@('source:strong','source:weak','source:other-org','source:revoked','source:confidential');budget=[ordered]@{max_evidence_items=2};expires_at=$now.AddMinutes(10).ToString('o');status='issued'};$request=[ordered]@{request_id='r1';task_id='t1';agent_id='external-research';grant_id='g1';organization_id='org1';department_id='dept1';project_id='project1';device_id='device1';device_attestation='verified';purpose='sanitized research';risk_level='L3';target='external_agent';max_items=2;allowed_classifications=@('public','internal_sanitized','confidential_reference_only');now=$now.ToString('o')}
function C($id,$source,$class,$org,$state,$revoked,$semantic,$quality){[ordered]@{evidence_id=$id;source_ref=$source;version='v1';classification=$class;organization_id=$org;department_id='dept1';project_id='project1';state=$state;valid_from=$now.AddDays(-1).ToString('o');valid_to=$now.AddDays(1).ToString('o');retention_until=$now.AddDays(30).ToString('o');revoked_at=$revoked;verification_status='verified';content_sha256=$hash;sanitized_excerpt="sanitized-$id";semantic_score=$semantic;evidence_quality=$quality;freshness_score=.8;cost_efficiency=.8;risk_fit=.8}}
$candidates=[ordered]@{candidates=@((C strong source:strong internal_sanitized org1 current $null .8 .95),(C weak source:weak public org1 current $null .95 .4),(C other source:other-org public org2 current $null 1 1),(C revoked source:revoked public org1 current $now.ToString('o') 1 1),(C confidential source:confidential confidential_reference_only org1 current $null 1 1))};$rp=W request.json $request;$gp=W grant.json $grant;$cp=W candidates.json $candidates;$result=&$runner -RequestPath $rp -GrantPath $gp -CandidatePath $cp -PassThru|ConvertFrom-Json
$bad=$request.PSObject.Copy();$bad.device_id='other-device';$bp=W bad-request.json $bad;$badOut=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $runner -RequestPath $bp -GrantPath $gp -CandidatePath $cp -PassThru 2>&1;$badCode=$LASTEXITCODE
$cases=@([pscustomobject]@{name='mandatory_filter_runs_before_ranking';passed=($result.policy_filter_applied_before_ranking-and$result.eligible_count-eq2-and$result.denied_count-eq3)},[pscustomobject]@{name='external_agent_gets_only_sanitized_pack';passed=(@($result.evidence_pack).Count-eq2-and@($result.evidence_pack.classification|?{$_-notin@('public','internal_sanitized')}).Count-eq0)},[pscustomobject]@{name='evidence_quality_can_beat_higher_semantic_score';passed=($result.evidence_pack[0].evidence_id-eq'strong')},[pscustomobject]@{name='external_agent_never_gets_search_or_raw_paths';passed=(-not$result.search_capability_granted-and-not$result.raw_paths_returned-and-not$result.raw_private_content_returned)},[pscustomobject]@{name='organization_and_revocation_fail_closed';passed=(@($result.denied_candidates|?{$_.evidence_id-in@('other','revoked')}).Count-eq2)},[pscustomobject]@{name='device_mismatch_denied_before_candidates';passed=($badCode-ne0)});$failed=@($cases|?{-not$_.passed});$r=[pscustomobject]@{passed=($failed.Count-eq0);cases=$cases;external_calls=$false;permissions_granted=$false};if($PassThru){$r|ConvertTo-Json -Depth 10}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Enterprise data admission regression failed: '+(($failed.name)-join', '))}
