<#
.SYNOPSIS
  Validates employee, Agent, model, work-order, and Grant separation of duties.
#>
param([Parameter(Mandatory=$true)][string]$ContractPath,[switch]$PassThru)
$ErrorActionPreference='Stop';$c=Get-Content -LiteralPath $ContractPath -Raw -Encoding UTF8|ConvertFrom-Json;$issues=[System.Collections.Generic.List[string]]::new();$required=@('collaboration_id','task_id','fusion_id','risk_level','manager_employee_id','final_adoption_authority','direct_agent_to_agent','status');foreach($f in $required){if($null-eq$c.$f-or[string]::IsNullOrWhiteSpace([string]$c.$f)){[void]$issues.Add($f+'_required')}}
$parts=@($c.participants);if($parts.Count-lt4){[void]$issues.Add('manager_two_candidates_verifier_and_adversarial_required')};$roles=@($parts.role);foreach($r in @('manager','candidate','independent_verifier','adversarial_checker')){if($roles-notcontains$r){[void]$issues.Add($r+'_required')}}
foreach($p in $parts){foreach($f in @('role','employee_id','agent_id','model_id','model_version','provider_family','error_group','work_order_ref','grant_ref')){if($null-eq$p.$f-or[string]::IsNullOrWhiteSpace([string]$p.$f)){[void]$issues.Add('participant_'+$f+'_required')}}}
$candidates=@($parts|?{$_.role-eq'candidate'});$reviewers=@($parts|?{$_.role-in@('independent_verifier','adversarial_checker')});if([string]$c.risk_level-eq'L3'-and$candidates.Count-lt2){[void]$issues.Add('L3_requires_two_candidates')};if(@($candidates.error_group|Sort-Object -Unique).Count-lt2){[void]$issues.Add('candidate_error_groups_not_independent')};if(@($parts.grant_ref|Sort-Object -Unique).Count-ne$parts.Count){[void]$issues.Add('grant_reuse_prohibited')};if(@($parts.agent_id|Sort-Object -Unique).Count-ne$parts.Count){[void]$issues.Add('agent_role_reuse_prohibited')}
foreach($reviewer in $reviewers){if(@($candidates.employee_id)-contains$reviewer.employee_id){[void]$issues.Add('candidate_employee_cannot_review_self')}};if([string]$c.direct_agent_to_agent-ne'deny'){[void]$issues.Add('direct_agent_to_agent_must_be_denied')};if([string]$c.final_adoption_authority-notin@('qianlima_broker','named_human')){[void]$issues.Add('invalid_final_adoption_authority')}
$result=[ordered]@{status=if($issues.Count){'rejected'}else{'validated'};collaboration_id=$c.collaboration_id;issues=@($issues);fan_in_owner='qianlima_broker';authority_expanded=$false;external_calls=$false;permissions_granted=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{[PSCustomObject]$result|Format-List};if($issues.Count){exit 1}
