<##
.SYNOPSIS
  Regression tests for vendor-neutral Enterprise MCP governance.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$contract=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'enterprise-mcp-platform-contract.json') -Raw -Encoding UTF8|ConvertFrom-Json;$gate=Join-Path $PSScriptRoot 'invoke-enterprise-mcp-gate.ps1';$cases=[System.Collections.Generic.List[object]]::new();function Add-Case([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})};function Run-Gate([string[]]$Arguments){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @Arguments -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$value=$null;try{$value=($out-join"`n")|ConvertFrom-Json}catch{};[PSCustomObject]@{code=$code;value=$value}}
Add-Case 'twelve_mcp_categories_defined' (@($contract.server_categories).Count-eq 12)
Add-Case 'direct_agent_mcp_requires_signed_session' ($contract.direct_agent_to_mcp-eq'allow_only_with_broker_signed_direct_session'-and $contract.direct_session.business_owner_approval_required-eq$true-and $contract.direct_session.connector_enforcement_required-eq$true)
$base=@('-Category','database_and_bi','-ServerId','db-mcp','-ServerVersion','1.0.0','-ExpectedVersion','1.0.0','-ToolId','query_sales','-GrantId','g1','-CredentialRef','db-read-ref','-DataScope','project1','-ServerEnabled','-ToolAllowlisted','-VerifiedAttestation','-BudgetAvailable')
$read=Run-Gate (@('-OperationClass','read_selected','-DataClassification','internal_sanitized','-NetworkZone','zone_2_internal')+$base);Add-Case 'generic_governed_read_allowed' ($read.code-eq 0-and $read.value.required_level-eq'L2')
$drift=Run-Gate @('-Category','search_and_research','-OperationClass','read_selected','-ServerId','search-mcp','-ServerVersion','2.0.0','-ExpectedVersion','1.0.0','-ToolId','search','-GrantId','g1','-CredentialRef','search-ref','-DataScope','public','-ServerEnabled','-ToolAllowlisted','-VerifiedAttestation','-BudgetAvailable');Add-Case 'version_drift_denied' ($drift.code-ne 0-and @($drift.value.reasons)-contains'mcp_server_version_drift')
$write=Run-Gate (@('-OperationClass','update')+$base);Add-Case 'ordinary_mcp_write_denied' ($write.code-ne 0-and @($write.value.reasons)-contains'dedicated_mcp_write_adapter_required')
$external=Run-Gate @('-Category','collaboration_and_messaging','-OperationClass','send','-DataClassification','confidential_reference_only','-NetworkZone','zone_4_external','-ServerId','msg-mcp','-ServerVersion','1','-ExpectedVersion','1','-ToolId','send','-GrantId','g1','-CredentialRef','msg-ref','-DataScope','task1','-ServerEnabled','-ToolAllowlisted','-VerifiedAttestation','-BudgetAvailable');Add-Case 'external_confidential_data_denied' ($external.code-ne 0-and @($external.value.reasons)-contains'external_mcp_data_class_denied')
$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq 0);cases=@($cases);mcp_called=$false;network_opened=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count-gt 0){throw "Enterprise MCP platform regression failed: $($failed.name-join', ')"}
