<##
.SYNOPSIS
  Regression tests for the reserved Lingxing MCP interface.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$map=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'lingxing-business-architecture.json') -Raw -Encoding UTF8|ConvertFrom-Json;$contract=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'lingxing-mcp-adapter-contract.json') -Raw -Encoding UTF8|ConvertFrom-Json;$gate=Join-Path $PSScriptRoot 'invoke-lingxing-mcp-gate.ps1';$cases=[System.Collections.Generic.List[object]]::new();function Add-Case([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})};function Run-Gate([string[]]$Arguments){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @Arguments -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$value=$null;try{$value=($out-join"`n")|ConvertFrom-Json}catch{};[PSCustomObject]@{code=$code;value=$value}}
Add-Case 'official_six_domain_map' (@($map.domains.PSObject.Properties).Count-eq 6)
Add-Case 'lingxing_is_data_plane_not_authority' ($map.positioning.lingxing-match'business data'-and $map.positioning.qianlima-match'governance control plane')
Add-Case 'interface_reserved_and_disabled' ($contract.status-eq'interface_reserved_not_connected'-and $contract.default_mode-eq'allowlist_read_only')
$disabled=Run-Gate @('-Domain','operations','-Mode','read','-ServerId','lingxing-readonly','-ToolId','get_orders','-GrantId','g1','-ShopScope','shop1','-MarketplaceScope','US','-CredentialRef','lingxing-read-ref');Add-Case 'disabled_server_denied' ($disabled.code-ne 0-and @($disabled.value.reasons)-contains'lingxing_mcp_server_disabled')
$read=Run-Gate @('-Domain','operations','-Mode','read','-ServerId','lingxing-readonly','-ToolId','get_orders','-GrantId','g1','-ShopScope','shop1','-MarketplaceScope','US','-CredentialRef','lingxing-read-ref','-ServerEnabled','-ToolAllowlisted','-VerifiedAttestation');Add-Case 'governed_read_interface_allowed' ($read.code-eq 0-and $read.value.required_level-eq'L2')
$write=Run-Gate @('-Domain','advertising','-Mode','write','-ServerId','lingxing-write','-ToolId','update_advertising','-GrantId','g1','-ShopScope','shop1','-MarketplaceScope','US','-CredentialRef','lingxing-write-ref','-ServerEnabled','-ToolAllowlisted','-VerifiedAttestation');Add-Case 'ordinary_mcp_write_denied' ($write.code-ne 0-and @($write.value.reasons)-contains'dedicated_lingxing_write_adapter_required')
$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq 0);cases=@($cases);mcp_called=$false;network_opened=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count-gt 0){throw "Lingxing MCP interface regression failed: $($failed.name-join', ')"}
