<##
.SYNOPSIS
  Regression tests for Joiner, Mover, and Leaver governance.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$creator=Join-Path $PSScriptRoot 'new-employee-lifecycle-request.ps1';$gate=Join-Path $PSScriptRoot 'invoke-employee-lifecycle-gate.ps1';$policy=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'employee-lifecycle-policy.json') -Raw -Encoding UTF8|ConvertFrom-Json;$cases=[System.Collections.Generic.List[object]]::new();function Add-Case([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})};function Gate([object]$Request){$json=$Request|ConvertTo-Json -Depth 8 -Compress;$value=& $gate -RequestJson $json -PassThru|ConvertFrom-Json;[PSCustomObject]@{code=if($value.status-eq'approved_plan'){0}else{1};value=$value}}
Add-Case 'employee_history_not_physically_deleted' ($policy.physical_employee_delete-eq'deny')
$join=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $creator -Action join -EmployeeId e1 -OrganizationId org1 -NewDepartmentId dept1 -NewManagerApprovalRef manager1 -PassThru|ConvertFrom-Json;$joinResult=Gate $join;Add-Case 'join_defaults_to_minimum_access' ($joinResult.code-eq 0-and @($joinResult.value.required_actions)-contains'deny_MCP_until_approved')
$transfer=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $creator -Action transfer -EmployeeId e1 -OrganizationId org1 -CurrentDepartmentId dept1 -NewDepartmentId dept2 -CurrentManagerApprovalRef old1 -NewManagerApprovalRef new1 -PassThru|ConvertFrom-Json;$transferResult=Gate $transfer;Add-Case 'transfer_revokes_before_regrant' ($transferResult.code-eq 0-and @($transferResult.value.required_actions)[1]-eq'revoke_old_department_grants')
$badOffboard=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $creator -Action offboard -EmployeeId e1 -OrganizationId org1 -CurrentManagerApprovalRef manager1 -PassThru|ConvertFrom-Json;$badResult=Gate $badOffboard;Add-Case 'offboard_requires_HR_and_handover' ($badResult.code-ne 0-and @($badResult.value.reasons)-contains'missing_HR_approval_ref'-and @($badResult.value.reasons)-contains'missing_handover_owner_id')
$offboard=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $creator -Action offboard -EmployeeId e1 -OrganizationId org1 -CurrentManagerApprovalRef manager1 -HRApprovalRef hr1 -HandoverOwnerId e2 -PassThru|ConvertFrom-Json;$offResult=Gate $offboard;Add-Case 'offboard_revokes_identity_Agent_MCP_and_credentials' ($offResult.code-eq 0-and @($offResult.value.required_actions)-contains'revoke_direct_MCP_sessions'-and @($offResult.value.required_actions)-contains'revoke_credentials')
$emergency=& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $creator -Action emergency_offboard -EmployeeId e1 -OrganizationId org1 -SecurityApprovalRef sec1 -PassThru|ConvertFrom-Json;$emergencyResult=Gate $emergency;Add-Case 'security_can_emergency_isolate' ($emergencyResult.code-eq 0-and @($emergencyResult.value.required_actions)-contains'isolate_devices')
$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq 0);cases=@($cases);changes_applied=$false;external_calls=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count-gt 0){throw "Employee lifecycle regression failed: $($failed.name-join', ')"}
