<# .SYNOPSIS Offline regression for the reserved Obsidian connector interface. #>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$contract=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'obsidian-connector-contract.json') -Raw -Encoding UTF8|ConvertFrom-Json;$registry=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'obsidian-connector-registry.example.json') -Raw -Encoding UTF8|ConvertFrom-Json;$gate=Join-Path $PSScriptRoot 'invoke-obsidian-connector-gate.ps1';$cases=[System.Collections.Generic.List[object]]::new()
function Run([string[]]$a){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @a -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$v=$null;try{$v=($out-join"`n")|ConvertFrom-Json}catch{};[pscustomobject]@{code=$code;value=$v}}
function Add($n,$p){$cases.Add([pscustomobject]@{name=$n;passed=[bool]$p})}
Add 'interface_reserved_and_disabled' ($contract.status-eq'interface_reserved_not_connected'-and$registry.connectors[0].enabled-eq$false)
$base=@('-Operation','read_selected_note','-ConnectorId','obsidian-local','-TaskId','t1','-AgentId','a1','-GrantId','g1','-VaultRef','vault:knowledge','-NoteRef','业务/报告.md','-DataClassification','internal_sanitized')
$disabled=Run $base;Add 'disabled_connector_denied' ($disabled.code-ne0-and@($disabled.value.reasons)-contains'obsidian_connector_disabled')
$read=Run ($base+@('-ConnectorEnabled','-VerifiedAttestation'));Add 'selected_markdown_read_allowed_at_L2' ($read.code-eq0-and$read.value.required_level-eq'L2'-and$read.value.vault_accessed-eq$false)
$escape=Run @('-Operation','read_selected_note','-ConnectorId','obsidian-local','-TaskId','t1','-AgentId','a1','-GrantId','g1','-VaultRef','vault:knowledge','-NoteRef','../secret.md','-DataClassification','internal_sanitized','-ConnectorEnabled','-VerifiedAttestation');Add 'scope_escape_denied' ($escape.code-ne0-and@($escape.value.reasons)-contains'note_scope_denied')
$plugin=Run @('-Operation','install_plugin','-ConnectorId','obsidian-local','-TaskId','t1','-AgentId','a1','-GrantId','g1','-VaultRef','vault:knowledge','-NoteRef','业务/报告.md','-DataClassification','internal_sanitized','-ConnectorEnabled','-VerifiedAttestation');Add 'plugin_install_always_denied' ($plugin.code-ne0-and@($plugin.value.reasons)-contains'operation_always_denied')
$write=Run @('-Operation','update_note','-ConnectorId','obsidian-local','-TaskId','t1','-AgentId','a1','-GrantId','g1','-VaultRef','vault:knowledge','-NoteRef','业务/报告.md','-DataClassification','internal_sanitized','-ConnectorEnabled','-VerifiedAttestation');Add 'ordinary_write_denied_and_escalated_to_L4' ($write.code-ne0-and$write.value.required_level-eq'L4'-and@($write.value.reasons)-contains'dedicated_obsidian_write_adapter_required')
$failed=@($cases|?{-not$_.passed});$r=[pscustomobject]@{passed=($failed.Count-eq0);cases=@($cases);vault_accessed=$false;mcp_called=$false;network_opened=$false;write_performed=$false};if($PassThru){$r|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count){throw('Obsidian connector regression failed: '+(($failed.name)-join', '))}
