<##
.SYNOPSIS
  Regression tests for commerce lifecycle, cadence, profit, and compliance MCP.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$model=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'commerce-operating-model.json') -Raw -Encoding UTF8|ConvertFrom-Json;$policy=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'compliance-mcp-policy.json') -Raw -Encoding UTF8|ConvertFrom-Json;$gate=Join-Path $PSScriptRoot 'invoke-compliance-mcp-gate.ps1';$cases=[System.Collections.Generic.List[object]]::new();function Add-Case([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})};function Run-Gate([string[]]$Arguments){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @Arguments -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$value=$null;try{$value=($out-join"`n")|ConvertFrom-Json}catch{};[PSCustomObject]@{code=$code;value=$value}}
Add-Case 'full_lifecycle_defined' (@($model.lifecycle).Count-eq 5-and @($model.lifecycle.modules)-contains'advertising'-and @($model.lifecycle.modules)-contains'after_sales')
Add-Case 'reports_and_plans_defined' (@($model.cadence.PSObject.Properties.Name)-contains'daily_report'-and @($model.cadence.PSObject.Properties.Name)-contains'annual_plan')
Add-Case 'five_profit_periods_defined' (@($model.profit_settlement.PSObject.Properties).Count-eq 5)
Add-Case 'monthly_profit_is_controlled_close' ($model.profit_settlement.monthly_profit.status-eq'controlled_close'-and $model.profit_settlement.monthly_profit.independent_verification-eq$true)
$read=Run-Gate @('-Domain','tax','-Operation','prepare_draft','-McpServerId','tax-mcp','-GrantId','g1','-OfficialSourceRefs','source1','-CredentialRef','tax-read-ref','-ServerAllowlisted');Add-Case 'compliance_draft_is_L3' ($read.code-eq 0-and $read.value.required_level-eq'L3')
$submit=Run-Gate @('-Domain','customs','-Operation','submit_official','-McpServerId','customs-mcp','-GrantId','g1','-OfficialSourceRefs','source1','-CredentialRef','customs-submit-ref','-ServerAllowlisted');Add-Case 'ordinary_mcp_cannot_submit' ($submit.code-ne 0-and @($submit.value.reasons)-contains'dedicated_submission_adapter_required')
$approved=Run-Gate @('-Domain','customs','-Operation','submit_official','-McpServerId','customs-mcp','-GrantId','g1','-OfficialSourceRefs','source1','-CredentialRef','customs-submit-ref','-ServerAllowlisted','-DedicatedSubmissionAdapter','-ResponsibleOwnerId','owner1','-ResponsibleOwnerRole','customs_owner','-HumanApprovalRef','approval1','-IdempotencyKey','idem1','-CompensationPlanRef','amend1');Add-Case 'responsible_customs_owner_can_authorize_L4' ($approved.code-eq 0-and $approved.value.business_owner_required-eq$false)
$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq 0);cases=@($cases);mcp_called=$false;files_written=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count-gt 0){throw "Commerce operating model regression failed: $($failed.name-join', ')"}
