<##
.SYNOPSIS
  Regression tests for Enterprise L0-L4 and responsibility-routed approvals.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$gate=Join-Path $PSScriptRoot 'invoke-enterprise-task-gate.ps1';$cases=[System.Collections.Generic.List[object]]::new()
function Run-Gate([string[]]$Arguments){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$output=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @Arguments -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$value=$null;try{$value=($output-join"`n")|ConvertFrom-Json}catch{};[PSCustomObject]@{exit_code=$code;value=$value}}
function Add-Case([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})}
$base=@('-TenantId','t1','-OrganizationId','o1','-EmployeeId','e1','-DeviceId','d1','-ProjectId','p1','-CostCenter','c1','-GrantId','g1','-AttestationStatus','verified')
$l0=Run-Gate @('-RequestedLevel','L0','-DataClassification','public');Add-Case 'enterprise_L0_public_allowed' ($l0.exit_code-eq 0)
$personal=Run-Gate @('-RequestedLevel','L2','-ClassificationEdition','personal');Add-Case 'personal_classification_rejected' ($personal.exit_code-ne 0-and @($personal.value.reasons)-contains'personal_classification_has_no_enterprise_authority')
$artifact=Run-Gate (@('-RequestedLevel','L2','-ActionType','task_artifact_write','-AgentTrust','T1')+$base);Add-Case 'task_artifact_write_is_L2' ($artifact.exit_code-eq 0-and $artifact.value.effective_level-eq'L2')
$internal=Run-Gate (@('-RequestedLevel','L3','-ActionType','internal_project_upload','-AgentTrust','T2','-VerifierId','checker')+$base);Add-Case 'internal_project_upload_is_L3_without_boss' ($internal.exit_code-eq 0-and $internal.value.business_owner_required-eq$false)
$routine=Run-Gate (@('-RequestedLevel','L4','-ActionType','business_write','-ApprovalProfile','routine_reversible','-AgentTrust','T3','-VerifierId','checker','-HumanOwnerId','manager1','-ApproverIds','manager1','-ApproverRoles','department_manager','-SnapshotRef','s1','-RollbackRef','r1')+$base);Add-Case 'routine_L4_one_responsible_manager' ($routine.exit_code-eq 0-and $routine.value.business_owner_required-eq$false)
$batch=Run-Gate (@('-RequestedLevel','L4','-ActionType','erp_write','-ApprovalProfile','routine_reversible','-AgentTrust','T3','-VerifierId','checker','-HumanOwnerId','manager1','-BatchApprovalId','batch1','-BatchApprovalStatus','valid','-WithinApprovedThreshold','-SnapshotRef','s1','-RollbackRef','r1')+$base);Add-Case 'routine_L4_valid_batch_without_per_action_click' ($batch.exit_code-eq 0-and $batch.value.approval_route-eq'valid_batch_approval')
$financial=Run-Gate (@('-RequestedLevel','L4','-ActionType','purchase','-ApprovalProfile','financial_material','-ThresholdExceeded','-AgentTrust','T3','-VerifierId','checker','-HumanOwnerId','finance1','-ApproverIds','finance1','-ApproverRoles','finance_owner','-SnapshotRef','s1','-RollbackRef','r1')+$base);Add-Case 'financial_threshold_escalates_to_owner' ($financial.exit_code-ne 0-and @($financial.value.reasons)-contains'business_owner_required_above_threshold')
$governance=Run-Gate (@('-RequestedLevel','L4','-ActionType','governance_change','-ApprovalProfile','governance_critical','-AgentTrust','T3','-VerifierId','checker','-HumanOwnerId','sec1','-ApproverIds','sec1,boss1','-ApproverRoles','security_admin,business_owner','-SnapshotRef','s1','-RollbackRef','r1')+$base);Add-Case 'governance_requires_security_and_owner' ($governance.exit_code-eq 0-and $governance.value.business_owner_required-eq$true)
$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq 0);cases=@($cases);external_calls=$false;execution_authorized=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count-gt 0){throw "Enterprise task-level regression failed: $($failed.name-join', ')"}
