<##
.SYNOPSIS
  Regression tests for business-approved direct MCP sessions.
##>
param([switch]$PassThru)
$ErrorActionPreference='Stop';$gate=Join-Path $PSScriptRoot 'invoke-direct-mcp-session-gate.ps1';$contract=Get-Content -LiteralPath (Join-Path $PSScriptRoot 'direct-mcp-session-contract.json') -Raw -Encoding UTF8|ConvertFrom-Json;$cases=[System.Collections.Generic.List[object]]::new();function Add-Case([string]$Name,[bool]$Passed){$cases.Add([PSCustomObject]@{name=$Name;passed=$Passed})};function Run-Gate([string[]]$Arguments){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$out=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gate @Arguments -PassThru 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$value=$null;try{$value=($out-join"`n")|ConvertFrom-Json}catch{};[PSCustomObject]@{code=$code;value=$value}}
$expiry=(Get-Date).ToUniversalTime().AddMinutes(30).ToString('o');$base=@('-SessionGrantId','session1','-BusinessOwnerApprovalRef','approval1','-OrganizationId','org1','-EmployeeId','employee1','-TaskId','task1','-AgentId','agent1','-AgentVersion','1.0','-DeviceId','device1','-ServerId','mcp1','-ServerVersion','1.0','-ExpectedServerVersion','1.0','-ToolManifestHash','hash1','-ExpectedToolManifestHash','hash1','-AllowedTools','read_orders,read_inventory','-DataScope','shop1','-ExpiresAt',$expiry,'-GrantStatus','active','-ConnectorVerified','-BudgetAvailable')
Add-Case 'connector_stays_in_direct_path' ($contract.enforcement.path-eq'agent_to_local_governance_connector_to_mcp'-and $contract.enforcement.connector_checks_each_call-eq$true)
$valid=Run-Gate ($base+@('-RequestedTool','read_orders'));Add-Case 'approved_employee_direct_read_session_allowed' ($valid.code-eq 0-and $valid.value.employee_id-eq'employee1'-and $valid.value.central_broker_in_data_path-eq$false)
$missing=Run-Gate @('-SessionGrantId','session1','-TaskId','task1');Add-Case 'missing_owner_approval_denied' ($missing.code-ne 0-and @($missing.value.reasons)-contains'missing_business_owner_approval_ref')
$tool=Run-Gate ($base+@('-RequestedTool','delete_records'));Add-Case 'tool_scope_expansion_denied' ($tool.code-ne 0-and @($tool.value.reasons)-contains'requested_tool_outside_session_scope')
$write=Run-Gate ($base+@('-RequestedTool','read_orders','-WriteRequested'));Add-Case 'direct_session_does_not_inherit_write' ($write.code-ne 0-and @($write.value.reasons)-contains'direct_session_does_not_inherit_write_authority')
$failed=@($cases|Where-Object{-not $_.passed});$result=[PSCustomObject]@{passed=($failed.Count-eq 0);cases=@($cases);connection_opened=$false};if($PassThru){$result|ConvertTo-Json -Depth 8}else{$cases|Format-Table -AutoSize};if($failed.Count-gt 0){throw "Direct MCP session regression failed: $($failed.name-join', ')"}
